config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :offers, only: [:index, :show, :new, :create]
  resources :meetings
  resources :reviews, only: [:index, :show, :new, :create]
  resources :messages, only: [:create]
  resources :likes, only: [:index, :create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  has_many :messages
  has_many :reviews
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :meeting
  has_many :users
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :meetings
  has_many :likes
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :meeting

  validates :rating, inclusion: (0..5)
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tags_users
  has_many :users, through: :tags_users
end

app/models/tags_user.rb
class TagsUser < ApplicationRecord
  belongs_to :tag
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tags_users, dependent: :destroy
  has_many :tags, through: :tags_users
  has_many :offers
  has_many :meetings
  has_many :messages
  has_many :reviews
  has_many :likes


  validates :first_name, presence: true
  validates :last_name, presence: true

  after_create :init_tags_users
  after_update :edit_tags_users

  def init_tags_users
    self.init_tags.each do |tag_id|
      TagsUser.create(tag: Tag.find(tag_id), user: self)
    end
  end

  def edit_tags_users
    TagsUser.where(user_id: self.id).destroy_all
    self.init_tags.each do |tag_id|
      TagsUser.create(tag: Tag.find(tag_id), user: self)
    end
  end
  # validates :email, presence: true, uniqueness: true
  # validates :password, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :city, :age, :avatar_url, :init_tags => []])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :description, :city, :age, :avatar_url, :init_tags => []])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @offers = []
    Offer.all.each do |offer|
      offer.likes.each do |like|
        if like.user_id == current_user.id
          @offers << offer
        end
      end
    end
  end

  def create
    @like = Like.new(like_params)
    @like.user_id = current_user.id
    @like.save!
    if params[:whereami] == "offers"
      redirect_to offers_path
    elsif params[:whereami] == "likes"
      redirect_to likes_path
    end

  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    if params[:whereami] == "offers"
      redirect_to offers_path
    elsif params[:whereami] == "likes"
      redirect_to likes_path
    end
  end

  def like_params
    params.permit(:offer_id)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    @meetings = Meeting.all
  end

  def show
    @meeting = Meeting.find(params[:id])
    @message = Message.new
    @review = Review.new
  end

  def new
    @meeting = Meeting.new
    @offer = Offer.find(params[:offer_id])
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id
    @meeting.status = "pending"
    if @meeting.save!
      Message.create!(content: meeting_params[:content], user_id: current_user.id, meeting_id: @meeting.id) unless meeting_params[:content].empty?
      redirect_to meeting_path(@meeting)
    else
      render :show#:template => 'offers_controller/show'
    end
  end

  def update
    @meeting = Meeting.find(params[:id])
    if params[:commit] == "Accepter cette rencontre"
      @meeting.status = "accepted"
    elsif params[:commit] == "Refuser cette rencontre"
      @meeting.status = "refused"
    elsif params[:commit] == "Annuler cette rencontre"
      @meeting.status = "canceled"
    end
    @meeting.save

    redirect_to meetings_path
=begin       if @meeting.update_attributes(meeting_params)
        flash[:success] = "Object was successfully updated"

      else
        flash[:error] = "Something went wrong"
        redirect_to @meeting
      end
=end
  end

  private

  def meeting_params
    params.require(:meeting).permit(:date, :status, :content, :offer_id, :commit)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    @message.save! unless @message.content.blank?
    redirect_to meeting_path(message_params[:meeting_id])
  end

  private

  def message_params
    params.require(:message).permit(:content, :user_id, :meeting_id)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index

    if params[:query].present?
      sql_query = " \
      offers.title @@ :query \
      OR offers.availabilities @@ :query \
      OR users.city @@ :query \
      "
      @offers = Offer.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @offers = Offer.all
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @meeting = Meeting.new
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user_id = current_user.id
    if @offer.save!
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :availabilities, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(params_review)
    if @review.save
      flash[:success] = "Object successfully created"
      redirect_to @review.meeting
    else
      flash[:error] = "Something went wrong"
      redirect_to @review.meeting
    end
  end
  

  def index
    @reviews = Review.all
  end

  private

  def params_review
    params.require(:review).permit(:content, :rating, :destinataire, :user_id, :meeting_id)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdopteUnPote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre:wght@300&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/0a6dd84551.js" crossorigin="anonymous"></script>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">


  </head>

  <body>
    <%=  render "/layouts/shared/navbar" %>
  <!--   <br>
    <br>
    <br> -->
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_card.html.erb
<div class="card" id="card-<%=offer.id%>">

  <div class="image" style="background-image:linear-gradient(to bottom, rgba(0,0,0,0.1), rgba(0,0,0,0.2)), url( <%= offer.user.avatar_url %> )">

      <% like = Like.find_by(user_id: current_user.id, offer_id: offer.id) %>


      <% if like.nil? %>
        <%= link_to likes_path(offer_id: offer.id, whereami: whereami), method: :post, remote: true do %>
          <i class="far fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to like_path(like, whereami: whereami), method: :delete, remote: true do %>
          <i class="fas fa-heart"></i>
        <% end %>
      <% end %>

    <%= link_to offer_path(offer, current_user), style: 'text-decoration:none' do %>
      <h2> <%= name %> </h2>
      <p><i class="fas fa-map-marker-alt"></i> <%= city %> </p>
  </div>

  <div class="text">
    <h3> <%=  title %></h3>
    <div class="taglist">
      <% tags.each do |tag| %>
        <div class="tag"> <%= tag.name %> </div>
      <% end %>

    </div>
  </div>


<% sum = 0 %>
<% n = 0 %>
<% Review.where(destinataire: offer.user_id).each do |review| %>
  <% sum += review.rating %>
   <% n += 1 %>
<% end %>
<% average = n.zero? ? '-' : sum.fdiv(n) %>

  <div class="rating"> <i class="fas fa-star"></i> <%= average %> (<%= n %>)</div>
    <% end %>
  </div>

app/views/layouts/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">Adopte un pote</a>
  <div class="collapse navbar-collapse w-100 d-flex justify-content-between navbar-nav" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <div class="d-flex nav-item justify-content-between" style="width: 55%;">
    <% else %>
      <div class="d-flex nav-item justify-content-between" style="width: 19%; ">
    <% end %>
      <%= link_to "Accueil", root_path, class: "nav-link" %>
      <%= link_to "Trouver un poto", offers_path, class: "nav-link" %>
      <% if user_signed_in? %>
        <%= link_to "Proposer une offre", new_offer_path(current_user), class: "nav-link" %>
        <%= link_to "Mes RDV", meetings_path(current_user), class: "nav-link" %>
        <%= link_to "Mes coups de coeur", likes_path, class: "nav-link" %>
      <% end %>
    </div>
    <div class="d-flex ">
      <% if user_signed_in?  %>
      <%= link_to current_user.first_name, edit_user_registration_path(current_user) , class: "nav-link" %>
        <li class="nav-item dropdown">
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src=" <%= current_user.avatar_url%> " />
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", edit_user_registration_path(current_user), class: "dropdown-item"%>
            <%= link_to "Paramètres", offers_path, class: "dropdown-item"%>
            <%= link_to "Aide", user_session_path, class: "dropdown-item"%>
            <%= link_to "Déconnexion", destroy_user_session_path,  method: :delete  ,class: "dropdown-item"%>
         </div>
        </li>
      <% else%>
        <%= link_to "Se connecter",   new_user_session_path , class: "nav-link" %>
        <%= link_to "Créer un compte",   new_user_registration_path , class: "nav-link" %>
      <% end %>
    </div>
  </div>
</div>

<div class="below-navbar"></div>

app/views/layouts/shared/_panel.html.erb
<div class="contenant">

  <div class="panel">
    <div class="supperposition">
      <img class="avatar-medium"  src=" <%= current_user.avatar_url%> " />
      <img class="avatar-medium chevauche"  src=" <%= meeting.offer.user.avatar_url%> " />
    </div>

    <div class="contient">
      <div class="panel-text">
        <h3>Ton rendez-vous avec <%= meeting.offer.user.first_name %> </h3>
        <p class="ml-3">Le 04/03/2020 à <%= current_user.city %> </p>
      </div>

      <div class="status-pan">
        Status : <%= meeting.status  %> 
        <% if meeting.status == "pending" %>
          &#128528
        <% elsif meeting.status == "accepted" %>
          &#128525
        <% else %>
           &#128557
        <% end %>
          
      </div>
    </div>
  </div>

</div>

app/views/layouts/shared/_panel_offer.html.erb
<div class="contenant">

  <div class="panel">
    <div class="supperposition">
      <img class="avatar-medium"  src=" <%= current_user.avatar_url%> " />
      <img class="avatar-medium chevauche"  src=" <%= meeting.user.avatar_url%> " />
    </div>

    <div class="contient">
      <div class="panel-text">
        <h3>Ton rendez-vous avec <%= meeting.user.first_name %> </h3>
        <p class="ml-3">Le 04/03/2020 à <%= current_user.city %> </p>
      </div>

      <div class="status-pan">
        Status : <%= meeting.status  %>
        <% if meeting.status == "pending" %>
          &#128528
        <% elsif meeting.status == "accepted" %>
          &#128525
        <% else %>
           &#128557
        <% end %>

      </div>
    </div>
  </div>

</div>

app/views/layouts/shared/_panel_user.html.erb
<div class="contenant">

  <div class="panel">
    <div class="supperposition">
      <img class="avatar-medium"  src=" <%= current_user.avatar_url%> " />
      <img class="avatar-medium chevauche"  src=" <%= meeting.offer.user.avatar_url%> " />
    </div>

    <div class="contient">
      <div class="panel-text">
        <h3>Ton rendez-vous avec <%= meeting.offer.user.first_name %> </h3>
        <p class="ml-3">Le 04/03/2020 à <%= meeting.offer.user.city %> </p>
      </div>

      <div class="status-pan">
        Status : <%= meeting.status  %>
        <% if meeting.status == "pending" %>
          &#128528
        <% elsif meeting.status == "accepted" %>
          &#128525
        <% else %>
           &#128557
        <% end %>

      </div>
    </div>
  </div>

</div>

app/views/layouts/shared/_reviews.html.erb
<div class="rating-board">
  <%if current_user == @meeting.user  %>
  <h4><%= "les reviews de #{@meeting.offer.user.first_name}" %></h4>
  <% Review.where(destinataire: @meeting.offer.user_id).each do |review| %>
    <div class="review">

      <div class="sender">
        <h5> <img class="avatar ml-3"  src=" <%= User.find(review.user_id).avatar_url %> " /> <%= User.find(review.user_id).first_name %> </h5>
        <h6><%= review.rating %> / 5</h6>
      </div>

      <p class="ml-4 mt-2"><%= review.content %></p>
      <p class="date-message">postée le <%= review.created_at.strftime("%d-%m-%Y") %> </p>
    </div>
    <% end %>

  <% else %>

    <% @meeting.user.reviews.each do |review| %>
      <%= review.rating %>
      <%= review.content %>
    <% end %>
  <% end %>
</div>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/index.html.erb
<div class="container" style="width:1000px; margin: 10px auto;">
  <h2 style="text-align: center; margin-bottom: 20px;">Mes coups de <i class="fas fa-heart"></i>:</h2>
  <div class="index">
    <% @offers.each do |offer| %>
      <%= render "/layouts/shared/card", name: offer.user.first_name, city: offer.user.city, title: offer.title, tags: offer.user.tags, offer: offer, whereami: "likes" %>

    <% end %>
  </div>
</div>

app/views/meetings/index.html.erb
<!-- edit.html.erb -->


<div style="height: 20px"></div>

<% current_user.meetings.each do |meeting| %>
  <%= link_to meeting_path(meeting, current_user), style: 'text-decoration:none' do %>
    <%= render "/layouts/shared/panel_user", meeting: meeting %>
  <% end %>

<% end %>

<br>


<div class=bottom-card>
<h1>Tes RDV en tant que poto:</h1>
</div>


<% Meeting.where(offer_id:current_user.id).each do |meeting| %>
  <%= link_to meeting_path(meeting, current_user), style: 'text-decoration:none' do %>
    <%= render "/layouts/shared/panel_offer", meeting: meeting %>
  <% end %>

<% end %>

</div>

app/views/meetings/show.html.erb
<div style="height: 10px"></div>

<div class="wrapper-header">
  <h5> <%= link_to "< Retour aux RDVs", meetings_path, class: "btn btn-info rdv" %> </h5>
</div>

  <div class=wrapper-global>
    <div class="wrapper-header-meeting">
      <div class="superposition">
        <div style="height: 15px"></div>
        <% if current_user.id == @meeting.user_id %>
          <img class="avatar-large-bordered" src="<%=@meeting.user.avatar_url%>"  alt="user avatar">
          <img class="avatar-large-bordered chevauche-big" src="<%=@meeting.offer.user.avatar_url%>"  alt="user avatar">
        <% else %>
          <img class="avatar-large-bordered" src="<%=@meeting.offer.user.avatar_url%>" alt="user avatar">
          <img class="avatar-large-bordered chevauche-big" src="<%=@meeting.user.avatar_url%>"  alt="user avatar">
        <% end %>
      </div>
    </div>

<div style="height: 20px"></div>

    <div class=details-center>
    <% if current_user.id == @meeting.user_id %>
      <h3 style="font-family: 'Frank Ruhl Libre', serif;">Ta rencontre avec <%= @meeting.offer.user.first_name %></h3>
    <% else %>
      <h3> Ta rencontre avec <%= @meeting.user.first_name %></h3>
    <% end %>
    <h4 style="font-family: 'Frank Ruhl Libre', serif;">Le <%= "#{@meeting.date.to_s[8,2]}/#{@meeting.date.to_s[5,2]}/#{@meeting.date.to_s[0,4]}"%> à <%= @meeting.offer.user.city %></h4>
      <div class="status-pan">
          Status : <%= @meeting.status  %>
          <% if @meeting.status == "pending" %>
            &#128528
          <% elsif @meeting.status == "accepted" %>
            &#128525
          <% else %>
            &#128557
          <% end %>
      </div>
    </div>
    <div style="height: 10px"></div>
  </div>


<div class="container-btn">
  <div class="btn">
    <div class=btn-center>

    <% if current_user.id == @meeting.offer.user_id %>
      <%= simple_form_for @meeting do |f| %>
        <%= f.button :submit, "Accepter cette rencontre", class: "btn btn-info"%>
        <%= f.button :submit, "Refuser cette rencontre", class: "btn btn-info"%>
      <% end %>
    <% else %>
      <%= simple_form_for @meeting do |f| %>
          <%= f.button :submit, "Annuler cette rencontre", class: "btn btn-info"%>
        <% end %>
      <% end %>

    </div>
  </div>
</div>


<div class="core"> 
  <div class="chat">
    <div class="wrapper-global-messages">
      <div class="wrapper-messages">
        <% @meeting.messages.each do |message| %>
          <div class="wrapper-message">
            <div class="wrapper-message-header">
              <img class="avatar" src="<%=User.find(message.user_id).avatar_url%>"  alt="user avatar">
              <div><%= User.find(message.user_id).first_name%>, le <%=message.created_at.strftime("%d-%m-%Y")%> à <%= message.created_at.strftime("%H:%M") %></div>
            </div>
            <div class="wrapper-message-content">
              <%= message.content %>
            </div>
          </div>
          <br>
        <% end %>
      </div>
    </div>

    <br>


    <div class="wrapper-global-messages">
        <%= simple_form_for @message, class:"wrapper-send-message" do |f| %>
            <%= f.input :content, label: "Ton message :", :input_html => {:style=> 'width: 600px'} %>
            <%= f.input :meeting_id, :as => :hidden, :input_html => { :value => @meeting.id } %>
            <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
            <div class="wrapper-button">
              <%= f.button :submit, "Envoyer", class:"btn btn-flat btn-send"%>
            </div>

      <% end %>
    </div>

    <br>
    <br>
  </div>

  <div class="reviews">
    <div class="rating-board">
    <%if current_user == @meeting.user  %>
    <h4><%= "les reviews de #{@meeting.offer.user.first_name}" %></h4>
    <% Review.where(destinataire: @meeting.offer.user_id).each do |review| %>
      <div class="review">

        <div class="sender">
          <h5> <img class="avatar ml-3"  src=" <%= User.find(review.user_id).avatar_url %> " /> <%= User.find(review.user_id).first_name %> </h5>
          <h6><%= review.rating %> / 5</h6>
        </div>

        <p class="ml-4 mt-2"><%= review.content %></p>
        <p class="date-message">postée le <%= review.created_at.strftime("%d-%m-%Y") %> </p>
      </div>
      <% end %>
      <div class="wrapper-global-messages-reviews">
      <%= simple_form_for @review, class:"wrapper-send-message" do |f| %>
            <%= f.input :rating, label: "Donne une note à #{@meeting.offer.user.first_name}" %>
            <%= f.input :content, label: "Ta review :" %>
            <%= f.input :meeting_id, :as => :hidden, :input_html => { :value => @meeting.id } %>
            <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
            <%= f.input :destinataire, :as => :hidden, :input_html => { :value => @meeting.offer.user_id } %>
            <div class="wrapper-button">
              <%= f.button :submit, "Envoyer", class:"btn btn-flat btn-send"%>
            </div>
      <% end %>
      </div>
            
    <% else %>

      <h4><%= "les reviews de #{@meeting.user.first_name}" %></h4>
      <% Review.where(destinataire: @meeting.user_id).each do |review| %>
        <div class="review">


          <div class="sender">
            <h5> <img class="avatar ml-3"  src=" <%= User.find(review.user_id).avatar_url %> " /> <%= User.find(review.user_id).first_name %> </h5>
            <h6><%= review.rating %> / 5</h6>
          </div>


          <p class="ml-4 mt-2"><%= review.content %></p>
          <p class="date-message">postée le <%= review.created_at.strftime("%d-%m-%Y") %> </p>
        </div>
      <% end %>
      <div class="wrapper-global-messages-reviews">
        <%= simple_form_for @review, class:"wrapper-send-message" do |f| %>
          <%= f.input :rating, label: "Donne une note à #{@meeting.user.first_name}" %>
          <%= f.input :content, label: "Ton retour d'expérience :" %>

          <%= f.input :meeting_id, :as => :hidden, :input_html => { :value => @meeting.id } %>
          <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
          <%= f.input :destinataire, :as => :hidden, :input_html => { :value => @meeting.user_id } %>
          <div class="wrapper-button">
            <%= f.button :submit, "Envoyer", class:"btn btn-flat btn-send"%>
          </div>
      </div>

      <% end %>




    <% end %>
  </div>
  
  </div>

</div>

app/views/offers/create.html.erb
<h1>Offers#create</h1>
<p>Find me in app/views/offers/create.html.erb</p>

app/views/offers/index.html.erb
<div class="container" style="width:1000px; margin: 10px auto;">
  <h2 style="text-align: center; margin-bottom: 20px;">Les potos dispos:</h2>
  <div class="index">
    <% @offers.each do |offer| %>
      <%= render "/layouts/shared/card", name: offer.user.first_name, city: offer.user.city, title: offer.title, tags: offer.user.tags, offer: offer, whereami: "offers" %>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="form">
  <div class="card-form">
    <h2 class="text-center">Que proposes-tu ? 😎</h2>
      <div class="input-info text-center">
        <%= simple_form_for @offer do |f| %>
        <%= f.input :title, label: "Ta punch-line :" %>
         </div>
      <div class="input-content text-center">
        <%= f.input :availabilities, label: "Tes dispos :" %>
      </div>
      <div class="input-info text-center">
        <%= f.button :submit, "Deviens un poto !", class:"btn-o btn btn-info btn-lg w-100" %>
        <% end %>
      </div>

  </div>
</div>

<div style="height: 10px"></div>

app/views/offers/show.html.erb
<div class="wrapper-header">
  <h5> <%= link_to "< Retour aux résultats", offers_path %> </h5>
</div>

<div class="wrapper-global">
  <div class="wrapper">
    <img class="avatar-large-bordered" src="<%= @offer.user.avatar_url %>" alt="user avatar">
    <div class="wrapper-profile-content">
      <h2> <%= @offer.user.first_name %> <i class="far fa-heart"></i> </h2>
      <p> <i class="fas fa-map-marker-alt"></i> Localisé(e) à <%= @offer.user.city %> </p>
      <h4> <em> "<%= @offer.title %>"</em> </h4>
      <div class="taglist">
        <% @offer.user.tags.each do |tag| %>
          <div class="tag"> <%= tag.name %> </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-offers-detail ">
  <div class="card-description">
    <h2>Ma description</h2>
    <hr/>
    <p> <%= @offer.user.description %> </p>
  </div>
    <div class="card-dispo">
      <h2>Mes dispos</h2>
      <hr/>
      <p> <%= @offer.availabilities %> </p>
    </div>
</div>
<% if user_signed_in? %>
  <div class="form-meeting">
     <div class="card-form">
        <h2 class="text-center">Ecris un message à ton futur poto :tada:</h2>
          <div class="input-info text-center">
            <%= simple_form_for @meeting do |f| %>
            <%= f.input :date, label: "Propose une date:" %>
            </div>
            <div class="input-content text-center">
            <%= f.input :content, label: "Envoie un petit message à ton poto:" %>
          </div>
            <div class="input-info text-center">
            <%= f.input :offer_id, :as => :hidden, :input_html => { :value => @offer.id } %>
           <%= f.button :submit, "Envoyer", class:"btn btn-flat w-90" %>
           <% end %>
          </div>
      </div>
  </div>
<% else %>
  <h3 style="text-align: center; margin-top: 30px;"> Connecte-toi pour écrire à ce poto et lui proposer un RDV ;) </h3>
<% end %>
<div style="height: 20px"></div>

app/views/pages/home.html.erb
<div class="background h-100">
 <div class="container find h-100" >
    <h1  style="">Tes potes ne sont pas assez cool ? Pas de problème !</h1>
    <div class="d-flex justify-content-center">
      <div class="searchbar">
        <%= form_tag offers_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "search_input",
          placeholder: "Trouve ton poto."
          %>

            <%= submit_tag "", class: "d-none" %>
            <%= icon("fas" ,"search search_icon") %>


        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>